### ISSUE TITLE
Implement WIP page

### ISSUE THREAD

**Issue by edoomm** [rebo-it/prototypes#16]
### TODO

- [ ] Implement `"En construcción..."` page based on **figma** mock-up
- [ ] Implement with `bootstrap`
- [ ] Implement with previous criteria #10 
- [ ] Change page title and page icon
